const fs = require('fs/promises');

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;

const fetchRepoDetails = async () => {
    let currBatch = 2025;

    for (reposList of Object.values(all_Repos)) {

        console.log("============ Batch : ", currBatch, " ====================")
        await fs.appendFile('finalData.txt', `============ Batch : ", ${currBatch}, " ====================\n`, 'utf8');
        currBatch -= 1;

        for (currRepo of reposList) {
            try {
                const split = currRepo.split("/")
                const response = await fetch(`https://api.github.com/repos/${split[3]}/${split[4]}`, {
                    headers: {
                        'Authorization': `token ${GITHUB_TOKEN}`,
                        'User-Agent': 'Node.js App'
                    }
                });
                if (!response.ok) {
                    console.warn(`Skipping ${currRepo}: ${response.status} ${response.statusText}`);
                    continue;
                }

                const languagesRes = await fetch(`https://api.github.com/repos/${split[3]}/${split[4]}/languages`, {
                    headers: {
                        'Authorization': `token ${GITHUB_TOKEN}`,
                        'User-Agent': 'Node.js App'
                    }
                });
                if (!languagesRes.ok) {
                    console.warn(`Skipping ${currRepo}: ${languagesRes.status} ${languagesRes.statusText}`);
                    continue;
                }

                const issuesRes = await fetch(`https://api.github.com/repos/${split[3]}/${split[4]}/issues`, {
                    headers: {
                        'Authorization': `token ${GITHUB_TOKEN}`,
                        'User-Agent': 'Node.js App'
                    }
                });
                if (!issuesRes.ok) {
                    console.warn(`Skipping ${currRepo}: ${issuesRes.status} ${issuesRes.statusText}`);
                    continue;
                }

                const issues = await issuesRes.json();
                let issuesCount = 0;
                let goodFirstIssuesCount = 0;

                for (issue of issues) {
                    if (issue.state != "open") continue
                    issuesCount += 1;

                    if (issue.labels.length == 0) continue;
                    for (label of issue.labels) {
                        if (label.name.toLowerCase().includes("good")) {
                            goodFirstIssuesCount += 1;
                            break;
                        }
                    }
                }

                const langData = await languagesRes.json();
                const data = await response.json();

                const requiredData = {
                    title: data.name,
                    desc: data.description,
                    avatar: data.owner.avatar_url,
                    languages: langData,
                    forks: data.forks_count,
                    stars: data.stargazers_count,
                    issues: issuesCount,
                    goodFirstIssues: goodFirstIssuesCount
                }
                await fs.appendFile('finalData.txt', `${JSON.stringify(requiredData)},\n`, 'utf8');
            } catch (e) {
                console.log("============ API didn't worked for :", currRepo);
                console.error(e)
            }
        }

        await fs.appendFile('finalData.txt', `===================================================\n\n`, 'utf8');
    }
}

// fetchRepoDetails()

const fetchRealRepos = async () => {
    for (ycBatch of Object.values(allYC_Companies)) {
        const list = ycBatch.list;
        let currBatch = 2025;

        console.log("============ Batch : ", currBatch, " ====================")
        await fs.appendFile('example.txt', `============ Batch : ", ${currBatch}, " ====================\n`, 'utf8');
        currBatch -= 1;
        let count = 0;

        for (startup of list) {
            const split = startup.split("/");
            if (split.length > 4) {
                await fs.appendFile('example.txt', `"${startup}",\n`, 'utf8');
                count += 1;
                continue;
            };

            const org = split[3];
            try {
                const repos = await fetch(`https://api.github.com/users/${org}/repos`, {
                    headers: {
                        'Authorization': `token ${GITHUB_TOKEN}`,
                        'User-Agent': 'Node.js App'
                    }
                });
                if (!repos.ok) {
                    console.warn(`Skipping ${startup}: ${repos.status} ${repos.statusText}`);
                    continue;
                }

                const data = await repos.json();

                let currMaxStar = 0;
                let popularRepo = "";
                for (repo of data) {
                    if (repo.forks_count === 0) continue;

                    if (repo.stargazers_count > currMaxStar) {
                        currMaxStar = repo.stargazers_count;
                        popularRepo = repo.html_url
                        count += 1
                    }
                }

                if (popularRepo) {
                    await fs.appendFile('example.txt', `'${popularRepo}',\n`, 'utf8');
                }
            } catch (e) {
                console.log("============ API didn't worked for :", startup);
                console.error(e)
            }
        }

        console.log(`Found ${count} actual repos out of ${list.length}`);
        await fs.appendFile('example.txt', `Found ${count} actual repos out of ${list.length}\n\n`, 'utf8');
        count = 0;
    }
}

// fetchRealRepos()

const allYC_Companies = {
    "YC_2025": {
        "info": "Found 57 out of 247 companies",
        "list": [
            'https://github.com/airweave-ai/airweave',
            'https://github.com/mlop-ai/mlop',
            'https://github.com/Mail-0',
            'https://github.com/Klavis-AI',
            'https://github.com/Alkali-Sim',
            'https://github.com/morphik-org/morphik-core',
            'https://github.com/tinfoilsh',
            'https://github.com/Operative-Sh',
            'https://github.com/better-auth',
            'https://github.com/attunehq',
            'https://github.com/pgdogdev/pgdog',
            'https://github.com/simstudioai/sim',
            'https://github.com/chonkie-ai',
            'https://github.com/orgs/almond-bot',
            'https://github.com/trycua/cua',
            'https://github.com/groundcontrol-software',
            'https://github.com/Avallon-Labs',
            'https://github.com/authed-dev',
            'https://github.com/getnao',
            'https://github.com/plexe-ai',
            'https://github.com/QFEX-org',
            'https://github.com/Beamlit',
            'https://github.com/mentralabs',
            'https://github.com/assistant-ui',
            'https://github.com/TrainLoop',
            'https://github.com/851-labs',
            'https://github.com/gregpr07/browser-use',
            'https://github.com/pig-dot-dev',
            'https://github.com/tensorpool/tensorpool',
            'https://github.com/roarkhq',
            'https://github.com/wild-card-ai',
            'https://github.com/mastra-ai',
            'https://github.com/artificial-societies',
            'https://github.com/infiniteagents',
            'https://github.com/confident-ai/deepeval',
            'https://github.com/agentin-ai',
            'https://github.com/rejot-dev',
            'https://github.com/augento',
            'https://github.com/Bindwell',
            'https://github.com/asteroidai',
            'https://github.com/Human-Data',
            'https://github.com/ZeroEntropy-AI',
            'https://github.com/nodable-labs',
            'https://github.com/maive-ai',
            'https://github.com/workweave',
            'https://github.com/a1baseai',
            'https://github.com/sublingual-ai/sublingual',
            'https://github.com/truffle-ai/truffle-ai-sdk',
            'https://github.com/superglue-ai/superglue',
            'https://github.com/subtrace/subtrace',
            'https://github.com/karoo-ca',
            'https://github.com/partcleda',
            'https://github.com/cartography-cncf/cartography',
            'https://github.com/quantstruct',
            'https://github.com/onlook-dev',
            'https://github.com/Leeroo-AI'
        ]
    },
    "YC_2024": {
        "info": "Found 147 out of 600 companies",
        "list": ['https://github.com/humanlayer',
            'https://github.com/synth-laboratories',
            'https://github.com/SRE-ai',
            'https://github.com/village-chat',
            'https://github.com/surgemsg',
            'https://github.com/diffusionstudio',
            'https://github.com/scrapybara',
            'https://github.com/Gecko-Security',
            'https://github.com/johnyeocx/autumn',
            'https://github.com/getdexter',
            'https://github.com/abundant-ai',
            'https://github.com/platus-inc',
            'https://github.com/lingodotdev',
            'https://github.com/ctgt-ai',
            'https://github.com/circlemind-ai/fast-graphrag',
            'https://github.com/vocera-ai',
            'https://github.com/vespperhq/vespper',
            'https://github.com/RevylAI',
            'https://github.com/coblocks',
            'https://github.com/getcho-org',
            'https://github.com/trypear/pearai-master',
            'https://github.com/outerport',
            'https://github.com/meltylabs',
            'https://github.com/freestyle-sh',
            'https://github.com/Arva-AI',
            'https://github.com/patched-codes',
            'https://github.com/General-Analysis/GA',
            'https://github.com/voideditor/void',
            'https://github.com/felafax',
            'https://github.com/rowboatlabs/rowboat',
            'https://github.com/diodeinc',
            'https://github.com/saldor-ai',
            'https://github.com/bucket-robotics',
            'https://github.com/blaze-xyz',
            'https://github.com/weavel-ai',
            'https://github.com/simplifine-llm/Simplifine',
            'https://github.com/autarcgmbh',
            'https://github.com/Kontigo-Inc/kontigo',
            'https://github.com/zeropathai',
            'https://github.com/ionworks',
            'https://github.com/heroui-inc',
            'https://github.com/lmnr-ai/lmnr',
            'https://github.com/eclipse-zenoh/zenoh',
            'https://github.com/theforecastingcompany',
            'https://github.com/exa-laboratories',
            'https://github.com/Pheat-AI',
            'https://github.com/ryx2',
            'https://github.com/conductorquantum',
            'https://github.com/opslane/opslane',
            'https://github.com/getAsterisk',
            'https://github.com/deepsilicon',
            'https://github.com/expandai',
            'https://github.com/mobility-solutions-inc',
            'https://github.com/fortress-build',
            'https://github.com/panoratech',
            'https://github.com/parity-ai',
            'https://github.com/Benchify',
            'https://github.com/zenbase-ai',
            'https://github.com/AutoPallet',
            'https://github.com/orgs/MerseOriginals',
            'https://github.com/gauge-sh/tach',
            'https://github.com/minusxai',
            'https://github.com/SnowPilotOrg',
            'https://github.com/aditya-nadkarni/spongecake',
            'https://github.com/edisonlabs-inc',
            'https://github.com/Storia-AI',
            'https://github.com/silurian-ai',
            'https://github.com/sorcerer-corp',
            'https://github.com/stack-auth',
            'https://github.com/orgs/Bayesline',
            'https://github.com/unslothai/unsloth',
            'https://github.com/HammingHQ',
            'https://github.com/EducatoAI',
            'https://github.com/comfy-deploy',
            'https://github.com/synnaxlabs',
            'https://github.com/glasskube/glasskube',
            'https://github.com/mem0ai',
            'https://github.com/miruml',
            'https://github.com/Angstrom-AI',
            'https://github.com/kscalelabs',
            'https://github.com/aidenybai/million',
            'https://github.com/useblacksmith',
            'https://github.com/tower-software-labs',
            'https://github.com/quivrhq/quivr',
            'https://github.com/renderlet',
            'https://github.com/Integuru-AI/Integuru',
            'https://github.com/openfoundry-ai',
            'https://github.com/Tyrus-Technologies',
            'https://github.com/OcularEngineering',
            'https://github.com/qaml-ai',
            'https://github.com/Titan-Systems',
            'https://github.com/stacksyncdata',
            'https://github.com/hatchet-dev',
            'https://github.com/getzep/zep',
            'https://github.com/Ligo-Biosciences/AlphaFold3',
            'https://github.com/circlebackai',
            'https://github.com/lumina-ai-inc/chunkr',
            'https://github.com/centauri-ai',
            'https://github.com/SoundryAI',
            'https://github.com/elodin-sys',
            'https://github.com/devflowinc/trieve',
            'https://github.com/toma-so/toma',
            'https://github.com/preloop',
            'https://github.com/superagent-ai/superagent',
            'https://github.com/PySpur-com/PySpur',
            'https://github.com/ellipsis-dev',
            'https://github.com/Lytix-Labs',
            'https://github.com/Pythagora-io',
            'https://github.com/openchatai',
            'https://github.com/organizations/aedilicrobots',
            'https://github.com/SalvyLTD',
            'https://github.com/phospho-app',
            'https://github.com/WhatsappX',
            'https://github.com/explodinggradients',
            'https://github.com/synchronicity-labs',
            'https://github.com/gventuri/pandas-ai',
            'https://github.com/motifland/markprompt',
            'https://github.com/guidelabs',
            'https://github.com/getomni-ai',
            'https://github.com/getzaymo',
            'https://github.com/atopile',
            'https://github.com/Artisan-AI',
            'https://github.com/octolane-org',
            'https://github.com/leapingio',
            'https://github.com/vercel/ai-chatbot',
            'https://github.com/buster-so/buster-platform',
            'https://github.com/nCompass-tech',
            'https://github.com/pretzelai/pretzelai',
            'https://github.com/momentic-ai',
            'https://github.com/reductoai',
            'https://github.com/nuanced-dev',
            'https://github.com/TracecatHQ/tracecat',
            'https://github.com/maihemlabs',
            'https://github.com/ion-design',
            'https://github.com/ubicloud/ubicloud',
            'https://github.com/greptileai',
            'https://github.com/ssoready',
            'https://github.com/relari-ai',
            'https://github.com/SciPhi-AI',
            'https://github.com/gumloop',
            'https://github.com/lanterndata',
            'https://github.com/onyx-dot-app/onyx',
            'https://github.com/gait-ai',
            'https://github.com/Patchwork-Tech',
            'https://github.com/OnedocLabs',
            'https://github.com/celest-dev',
            'https://github.com/quarylabs',
        ]
    },
    "YC_2023": {
        "info": "Found 118 out of 494 companies",
        "list": ['https://github.com/openpipe/openpipe',
            'https://github.com/codestoryai',
            'https://github.com/coba-ai',
            'https://github.com/orgs/Planetary-Computers/repositories',
            'https://github.com/Olio-Labs/olio',
            'https://github.com/usewalletkit',
            'https://github.com/StructuredLabs/preswald',
            'https://github.com/srcbookdev/srcbook',
            'https://github.com/FlowiseAI',
            'https://github.com/shadeform',
            'https://github.com/paradedb',
            'https://github.com/ueberdosis/tiptap',
            'https://github.com/RecipeUI/RecipeUI',
            'https://github.com/enfraxyz',
            'https://github.com/cedalio',
            'https://github.com/happyrobot-labs',
            'https://github.com/Langdock',
            'https://github.com/checkfragment',
            'https://github.com/sweepai/sweep',
            'https://github.com/Silimate',
            'https://github.com/trytrench/trench',
            'https://github.com/baserun-ai',
            'https://github.com/automorphic-ai',
            'https://github.com/run-converge',
            'https://github.com/CambioML',
            'https://github.com/khoj-ai/khoj',
            'https://github.com/kobalt-labs',
            'https://github.com/Trainy-ai',
            'https://github.com/pincites',
            'https://github.com/apoxy-dev',
            'https://github.com/srcpulse',
            'https://github.com/continuedev',
            'https://github.com/redotvideo',
            'https://github.com/metalware-inc',
            'https://github.com/refinedev',
            'https://github.com/epsilla-cloud',
            'https://github.com/Skyvern-AI/skyvern/tree/main/integrations/mcp',
            'https://github.com/Health-Harbor',
            'https://github.com/briefercloud',
            'https://github.com/shastahealth',
            'https://github.com/hegelai/prompttools',
            'https://github.com/Serra-Technologies',
            'https://github.com/obentohealth',
            'https://github.com/parea-ai',
            'https://github.com/sidhq',
            'https://github.com/tegonhq/tegon',
            'https://github.com/Revamp-AI',
            'https://github.com/datashare-public',
            'https://github.com/atla-ai',
            'https://github.com/opentoolsteam',
            'https://github.com/cedana',
            'https://github.com/magicloops',
            'https://github.com/dioxusLabs',
            'https://github.com/accendhq',
            'https://github.com/elyosenergy',
            'https://github.com/xeol-io',
            'https://github.com/twentyhq/twenty',
            'https://github.com/reworkd/AgentGPT',
            'https://github.com/artie-labs/transfer',
            'https://github.com/moonrepo',
            'https://github.com/BerriAI/litellm',
            'https://github.com/Atri-Labs/atrilabs-engine',
            'https://github.com/Escape-Technologies',
            'https://github.com/KoalaOps',
            'https://github.com/getmetal',
            'https://github.com/vocodedev/vocode-python',
            'https://github.com/thebabylonai',
            'https://github.com/fern-api/fern',
            'https://github.com/evefancom/evefan',
            'https://github.com/rivet-gg',
            'https://github.com/swishjam',
            'https://github.com/invopop',
            'https://github.com/keephq/keep',
            'https://github.com/playht',
            'https://github.com/sirdab',
            'https://github.com/uptrain-ai/uptrain',
            'https://github.com/odigos-io/odigos',
            'https://github.com/vitalizecare',
            'https://github.com/noya-app/noya',
            'https://github.com/koyweforest',
            'https://github.com/sage-ai-dev',
            'https://github.com/defog-ai',
            'https://github.com/boundaryml/baml',
            'https://github.com/Helicone/helicone',
            'https://github.com/IcePanel',
            'https://github.com/tableflowhq',
            'https://github.com/inkeep',
            'https://github.com/openmeterio',
            'https://github.com/langfuse/langfuse',
            'https://github.com/FrigadeHQ',
            'https://github.com/athina-ai',
            'http://github.com/adap/flower',
            'https://github.com/LinkGrep',
            'https://github.com/launchflow',
            'https://github.com/usecakework',
            'https://github.com/edgebitio',
            'https://github.com/mercoa-finance',
            'https://github.com/NangoHQ',
            'https://github.com/depot',
            'https://github.com/magicpatterns',
            'https://github.com/DrDroidLab',
            'https://github.com/triggerdotdev/trigger.dev',
            'https://github.com/traceloop',
            'https://github.com/matanolabs',
            'https://github.com/reflex-dev',
            'https://github.com/stackai',
            'https://github.com/middleware-labs',
            'https://github.com/unifyai',
            'https://github.com/tremorlabs/tremor',
            'https://github.com/PeerDB-io/peerdb#postgres-compatible-sql-interface-to-do-etl',
            'http://github.com/highlight/highlight',
            'https://github.com/dagworks-inc',
            'https://github.com/dashdive',
            'https://github.com/vangoai',
            'https://github.com/organizations/unhazeai',
            'https://github.com/defer-run',
            'https://www.github.com/technicianai',
            'https://github.com/blyssprivacy',
        ]
    },
    "YC_2022": {
        "info": "Found 86 out of 633 companies",
        "list": ['https://github.com/polymathrobotics',
            'https://github.com/integrated-reasoning',
            'https://github.com/wondercraft-ai',
            'https://github.com/Jasmine-Energy',
            'https://github.com/mendableai',
            'https://github.com/laminlabs',
            'https://github.com/kombohq',
            'https://github.com/ask-fini',
            'https://github.com/metriport/metriport',
            'https://github.com/mayahq',
            'https://github.com/Pluralith',
            'https://github.com/Mintplex-Labs',
            'https://github.com/Peoplebox',
            'https://github.com/nucleuscloud/neosync',
            'https://github.com/nostrapollo',
            'https://github.com/mmourafiq',
            'https://github.com/windmill-labs/windmill#how-to-self-host',
            'https://github.com/activepieces/activepieces',
            'https://github.com/codecrafters-io/build-your-own-x',
            'https://github.com/customeros/customeros',
            'https://github.com/tailor-platform',
            'https://github.com/dittofeed',
            'https://github.com/SuperpoweredAI',
            'https://github.com/versa-protocol',
            'https://github.com/withpoly',
            'https://github.com/medplum',
            'https://github.com/massdriver-cloud',
            'https://github.com/Reality-Defender',
            'https://github.com/alima-latam',
            'https://github.com/karatelabs',
            'https://github.com/gravitl',
            'https://github.com/VerdnHQ',
            'https://github.com/heptameta',
            'https://github.com/codec-hq',
            'https://github.com/ploomber',
            'https://github.com/ngrow',
            'https://github.com/decentxyz',
            'https://github.com/drifting-in-space',
            'https://github.com/propelauth',
            'https://github.com/argumentcomputer',
            'https://github.com/amalinvest',
            'https://github.com/iotflows',
            'https://github.com/CypherD-IO',
            'https://github.com/brainboard',
            'https://github.com/bemlo',
            'https://github.com/nullstone-io',
            'https://github.com/botcity-dev',
            'https://github.com/airworkhq',
            'https://github.com/simplifyd-systems',
            'https://github.com/HydrasDB',
            'https://github.com/PayCrunch-team',
            'https://github.com/tolahq',
            'https://github.com/voize-gmbh',
            'https://github.com/DigiventuresFintech',
            'https://github.com/tuva-health',
            'https://github.com/mintlify',
            'https://github.com/iomete',
            'https://github.com/bharatx-in',
            'https://github.com/pingdotgg',
            'https://github.com/flagright',
            'https://github.com/its-dart',
            'https://github.com/beam-cloud/beta9',
            'https://github.com/lancedb',
            'https://github.com/firezone',
            'https://github.com/elementary-data/elementary',
            'https://github.com/sribuu',
            'https://github.com/unlayer',
            'https://github.com/instant-labs',
            'https://github.com/vendoo',
            'https://github.com/in/mhamann',
            'https://github.com/policyfly',
            'https://github.com/KapitalTrading',
            'https://github.com/growthbook',
            'https://github.com/andisearch',
            'https://github.com/payloadcms',
            'https://github.com/hyperdxio',
            'https://github.com/Nara-Assistant',
            'https://github.com/requestly',
            'https://github.com/speechly',
            'https://github.com/extragoodlabs',
            'https://github.com/dev-tools-ai',
            'https://github.com/uselotus',
            'https://github.com/grai-io',
            'https://github.com/bricks-cloud/BricksLLM',
            'https://github.com/sematic-ai',
            'https://github.com/trytoolchest',
        ]
    },
    "YC_2021": {
        "info": "Found 143 out of 727 companies",
        "list": ['https://github.com/moxion-power',
            'https://github.com/careeristinc',
            'https://github.com/Odiggo/sullyai-copilot',
            'https://github.com/lightly-ai',
            'https://github.com/ahazou',
            'https://github.com/stepful',
            'https://github.com/evidence-dev',
            'https://github.com/bytebot-ai/bytebot',
            'https://github.com/suplias',
            'https://github.com/idemeum',
            'https://github.com/oneistox',
            'https://github.com/bloopai',
            'https://github.com/payzeio',
            'https://github.com/genomelink',
            'https://github.com/mach9robotics',
            'https://github.com/Examedi',
            'https://github.com/HykoAPI',
            'https://github.com/floatpays',
            'https://github.com/hit-pay',
            'https://github.com/Writesonic',
            'https://github.com/akute-health-inc',
            'https://github.com/adaptyvbio',
            'https://github.com/madebyendla',
            'https://github.com/appcumbuca',
            'https://github.com/evidentlyai',
            'https://github.com/zensors',
            'https://github.com/GetAleph',
            'https://github.com/formancehq',
            'https://github.com/mergentlabs',
            'https://github.com/cloudthread',
            'https://github.com/organizations/WarpBuilds',
            'https://github.com/DigiBuildOfficial',
            'https://github.com/cloudanix',
            'https://github.com/enso-org',
            'https://github.com/TestRigor',
            'https://github.com/Onebrief',
            'https://github.com/hyperbrowserai',
            'https://github.com/jovianhq',
            'https://github.com/secoda',
            'https://github.com/getlago',
            'https://github.com/snapcalorie',
            'https://github.com/StriveMath',
            'https://github.com/EchoesHQ',
            'https://github.com/joindeed',
            'https://github.com/firstquadrant-ai',
            'https://github.com/rootlyhq',
            'https://github.com/Flow-Club',
            'https://github.com/carbonfact',
            'https://github.com/stipop-development',
            'https://github.com/pipekit',
            'https://github.com/superwall',
            'https://github.com/legionhealth',
            'https://github.com/TalusBio',
            'https://github.com/hotgluexyz',
            'https://github.com/artilleryio',
            'https://github.com/openlayer-ai',
            'https://github.com/ollama/ollama',
            'https://github.com/magicbell-io',
            'https://github.com/reshapebiotech',
            'https://github.com/Haut-Technologies',
            'https://github.com/arpio',
            'https://github.com/waydevco',
            'https://github.com/avionschool',
            'https://github.com/runopsio',
            'https://github.com/djamoapp',
            'https://github.com/hubuc',
            'https://github.com/wasp-lang',
            'https://github.com/mystic-ai/pipeline',
            'https://github.com/UPchieve',
            'https://github.com/splinetool',
            'https://github.com/30SAS',
            'https://github.com/svix',
            'https://github.com/infracost',
            'https://github.com/chatwoot',
            'https://github.com/vuestorefront',
            'https://github.com/lunatic-solutions',
            'https://github.com/Zealth-AI',
            'https://github.com/basarooms',
            'https://github.com/compose-ai',
            'https://github.com/rulebricks',
            'https://github.com/tint-ai',
            'https://github.com/lastbit-io',
            'https://github.com/SimplifyJobs',
            'https://github.com/Codingal',
            'https://github.com/quiknode-labs',
            'https://github.com/quotabook',
            'https://github.com/sst',
            'https://github.com/homebaseio',
            'https://github.com/CoderHouse',
            'https://github.com/enode',
            'https://github.com/datrics-ai',
            'https://github.com/finary-wealth',
            'https://github.com/Greywing-Maritime',
            'https://github.com/BrioHR',
            'https://github.com/careweather',
            'https://github.com/getweweb',
            'https://github.com/mindee',
            'https://github.com/dashboardlabs',
            'https://github.com/fintoc-com',
            'https://github.com/vapiai',
            'https://github.com/FifthTry',
            'https://github.com/PerDiemInc',
            'https://github.com/bimaplan',
            'https://github.com/terapify',
            'https://github.com/encord-team',
            'https://github.com/segments-ai',
            'https://github.com/laudspeaker/laudspeaker',
            'https://github.com/spruceid',
            'https://github.com/curvenote',
            'https://github.com/aspen-cloud',
            'https://github.com/vogent',
            'https://github.com/ModernLoop',
            'https://github.com/SigNoz',
            'https://github.com/Taloflow',
            'https://github.com/humaans',
            'https://github.com/authzed',
            'https://github.com/abacum-io',
            'https://github.com/webiny',
            'https://github.com/warrant-dev',
            'https://github.com/arengu',
            'https://github.com/inaitech',
            'https://github.com/beeper',
            'https://github.com/pipebio',
            'https://github.com/kitemakerhq',
            'https://github.com/GoPreki',
            'https://github.com/pyroscope-io',
            'https://github.com/dyte-io',
            'https://github.com/ProcotoInc',
            'https://github.com/EmergeTools',
            'https://github.com/promotedai',
            'https://github.com/hyper',
            'https://github.com/opkit-co',
            'https://github.com/movingparts-io',
            'https://github.com/Hypercontext',
            'https://github.com/ivella',
            'https://github.com/Dataherald',
            'https://github.com/sturdy-dev/codeball-action',
            'https://github.com/Aerotime',
            'https://github.com/finantier',
            'https://github.com/milk-video',
            'https://github.com/finaryio',
            'https://github.com/sbxrobotics',
            'https://github.com/gonddo',
        ]
    },
    "YC_2020": {
        "info": "Found 96 out of 436 companies",
        "list": ['https://github.com/Whatnot-Inc',
            'https://github.com/hub-la',
            'https://github.com/heron-data',
            'https://github.com/Fieldguide',
            'https://github.com/MedPiperGlobal',
            'https://github.com/Lendtable',
            'https://github.com/spenmo',
            'https://github.com/mito-ds',
            'https://github.com/ready',
            'https://github.com/supabase',
            'https://github.com/Laylo',
            'https://github.com/orgs/formalco',
            'https://github.com/PANADATA',
            'https://github.com/scrimba',
            'https://github.com/Notabene-id',
            'https://github.com/tydo',
            'https://github.com/getjusto',
            'https://github.com/aristco',
            'https://github.com/humanloop',
            'https://github.com/speedscale',
            'https://github.com/FarmakoHealthcare',
            'https://github.com/bukuwarung',
            'https://github.com/getsafepay',
            'https://github.com/seamapi',
            'https://github.com/conta-simples',
            'https://github.com/questdb',
            'https://github.com/shuttle-hq',
            'https://github.com/AtoB-Developers',
            'https://github.com/lightdash',
            'https://github.com/datafold',
            'https://github.com/supertokens',
            'https://github.com/roboflow',
            'https://github.com/increase',
            'https://github.com/jitsucom',
            'https://github.com/ukama',
            'https://github.com/PerchCredit',
            'https://github.com/jet-admin',
            'https://github.com/YAtechnologies',
            'https://github.com/jenfi-eng',
            'https://github.com/MentenAI',
            'https://github.com/belvo-finance',
            'https://github.com/airbytehq',
            'https://github.com/TambuaHealth',
            'https://github.com/99minutos',
            'https://github.com/recallai',
            'https://github.com/Sakneen',
            'https://github.com/nplexbio',
            'https://github.com/dbrainio',
            'https://github.com/starkbank',
            'https://github.com/termiiwebtech',
            'https://github.com/Fondeadora',
            'https://github.com/openbiome',
            'https://github.com/raycast',
            'https://github.com/stayqrious',
            'https://github.com/deepsourcecorp',
            'https://github.com/upflowhq',
            'https://github.com/recurrency',
            'https://github.com/PostHog',
            'https://github.com/PhotoRoom',
            'https://github.com/ToDesktop',
            'https://github.com/dropbaseHQ',
            'https://github.com/alloy-automation',
            'https://github.com/voriteam',
            'https://github.com/buildbuddy-io',
            'https://github.com/cortexapps',
            'https://github.com/querypie/querypie-mcp-server',
            'https://github.com/signadot',
            'https://github.com/superfly',
            'https://github.com/benepass',
            'https://github.com/Basedash',
            'https://github.com/replicate',
            'https://github.com/acho-dev/acho-js#readme',
            'https://github.com/nextmv-io',
            'https://github.com/DeepMeditate',
            'https://github.com/Brokrete',
            'https://github.com/openunit',
            'https://github.com/segmed',
            'https://github.com/mindsdb',
            'https://github.com/porter-dev',
            'https://github.com/polytomic',
            'https://github.com/loophealth',
            'https://github.com/chaos-genius',
            'https://github.com/Hellosaurus',
            'https://github.com/zerostep-ai/zerostep',
            'https://github.com/Charityvest',
            'https://github.com/typedreamhq',
            'https://github.com/metaplane',
            'https://github.com/withfig',
            'https://github.com/piepacker',
            'https://github.com/streamdal',
            'https://github.com/webappio',
            'https://github.com/ClearMix',
            'https://github.com/gitduckhq',
            'https://github.com/carupi',
            'https://github.com/tridentbio',
            'https://github.com/datreeio'
        ]
    },
    "YC_2019": {
        "info": "Found 95 out of 370 companies",
        "list": ['https://github.com/OdekoTeam',
            'https://github.com/gathertown',
            'https://github.com/juzibot',
            'https://github.com/SequenceBio',
            'https://github.com/Breadfast',
            'https://github.com/taskade',
            'https://github.com/deepnote',
            'https://github.com/treble-ai',
            'https://github.com/VitauMX',
            'https://github.com/teamcurri',
            'https://github.com/zeroheight',
            'https://github.com/freshpaint-io',
            'https://github.com/paymongo',
            'https://github.com/ineventapp',
            'https://github.com/Recidiviz',
            'https://github.com/trella-app',
            'https://github.com/hightouchio',
            'https://github.com/fampay',
            'https://github.com/LineLeap',
            'https://github.com/wasmerio',
            'https://github.com/microverseinc',
            'https://github.com/Rutter',
            'https://github.com/kreativai',
            'https://github.com/rainbow-me',
            'https://github.com/entrc',
            'https://github.com/kubesail',
            'https://github.com/openreplay',
            'https://github.com/Localitos',
            'https://github.com/embrace-io',
            'https://github.com/trmlabs',
            'https://github.com/HackerYou',
            'https://github.com/wellprincipled',
            'https://github.com/kraftful',
            'https://github.com/MethodFi',
            'https://github.com/trycourier',
            'https://github.com/mightyapp',
            'https://github.com/oven-sh',
            'https://github.com/prenda-school',
            'https://github.com/memfault',
            'https://github.com/rct-ai',
            'https://github.com/numeroai',
            'https://github.com/truora',
            'https://github.com/cosmicjs',
            'https://github.com/votingworks',
            'https://github.com/marsauto',
            'https://github.com/dockup',
            'https://github.com/Frubana',
            'https://github.com/rune',
            'https://github.com/glideapps',
            'https://github.com/lezzoo',
            'https://github.com/emilabs',
            'https://github.com/kovihq',
            'https://github.com/mudrex',
            'https://github.com/alpacahq',
            'https://github.com/Upsolve',
            'https://github.com/owid',
            'https://github.com/dagger',
            'https://github.com/Superb-AI-Suite',
            'https://github.com/AuraVisionLabs',
            'https://github.com/DopplerHQ',
            'https://github.com/gordiansoftware',
            'https://github.com/bunkerhillhealth',
            'https://github.com/termius',
            'https://github.com/Supernova-Studio',
            'https://github.com/ashbyhq',
            'https://github.com/okteto',
            'https://github.com/demodesk',
            'https://github.com/saplingai',
            'https://github.com/WeatherCheck',
            'https://github.com/community-phone-company',
            'https://github.com/ThriveAgric',
            'https://github.com/GoLinks',
            'https://github.com/middesk',
            'https://github.com/WindwalkGames',
            'https://github.com/convictional',
            'https://github.com/sunsama',
            'https://github.com/ultralight-ux',
            'https://github.com/keepertax',
            'https://github.com/pachama',
            'https://github.com/Flockjay',
            'https://github.com/actiondesk',
            'https://github.com/popsql',
            'https://github.com/together-platform',
            'https://github.com/coursedog',
            'https://github.com/fuzzbuzz',
            'https://github.com/elpha-inc',
            'https://github.com/nomadrides',
            'https://github.com/multis',
            'https://github.com/tensil-ai',
            'https://github.com/lunasec-io',
            'https://github.com/dashblock',
            'https://github.com/narratorai',
            'https://github.com/basilica-ai',
            'https://github.com/DevFlight',
            'https://github.com/KopaHQ'
        ]
    },
    "YC_2018": {
        "info": "Found 70 out of 278 companies",
        "list": ['https://github.com/Groww',
            'https://github.com/newfront-insurance',
            'https://github.com/okcredit',
            'https://github.com/culdesac-labs',
            'https://github.com/ilabservice',
            'https://github.com/enveritas',
            'https://github.com/AnnieCannons',
            'https://github.com/cowrywise',
            'https://github.com/brainhi',
            'https://github.com/Skydropx',
            'https://github.com/eva-tech',
            'https://github.com/alphavantage',
            'https://github.com/rain-neuromorphics',
            'https://github.com/ajaibid',
            'https://github.com/duffelhq',
            'https://github.com/corvus-robotics',
            'https://github.com/easolhq',
            'https://github.com/AnimaApp',
            'https://github.com/meruhealth',
            'https://github.com/OpenPhone',
            'https://github.com/InscribeAI',
            'https://github.com/activeloopai',
            'https://github.com/RevenueCat',
            'https://github.com/federacy',
            'https://github.com/Modern-Treasury',
            'https://github.com/Curebase',
            'https://github.com/snackpass',
            'https://github.com/replit',
            'https://github.com/swayable',
            'https://github.com/Veriff',
            'https://github.com/Aerones-com',
            'https://github.com/erudifi',
            'https://github.com/captivateiq',
            'https://github.com/anjuna-security',
            'https://github.com/culturerobotics',
            'https://github.com/ProjectOpenSea',
            'https://github.com/safetywing',
            'https://github.com/delphia',
            'https://github.com/substackinc',
            'https://github.com/players-lounge',
            'https://github.com/treasuryprime',
            'https://github.com/JuniLearning',
            'https://github.com/supermedium',
            'https://github.com/BioRender-Team',
            'https://github.com/envkey',
            'https://github.com/vixur',
            'https://github.com/draftbit',
            'https://github.com/VantaInc',
            'https://github.com/nuvocargo',
            'https://github.com/modernhealth',
            'https://github.com/biobotanalytics',
            'https://github.com/nexgent',
            'https://github.com/simetrikinc',
            'https://github.com/coin-tracker',
            'https://github.com/sliteteam',
            'https://github.com/Worklytics',
            'https://github.com/shogun-toolbox',
            'https://github.com/sizigi',
            'https://github.com/quantstamp',
            'https://github.com/shelfengine',
            'https://github.com/hypcloud',
            'https://github.com/happilabs',
            'https://github.com/opticdev',
            'https://github.com/jidomaps',
            'https://github.com/Memora-Health',
            'https://github.com/sharpest-minds',
            'https://github.com/naborly',
            'https://github.com/radixbio',
            'https://github.com/reverielabs',
            'https://github.com/sketchbox3d'
        ]
    }
}

const all_Repos = {
    "YC_2025": [
        'https://github.com/airweave-ai/airweave',
        'https://github.com/mlop-ai/mlop',
        'https://github.com/Mail-0/Zero',
        'https://github.com/Klavis-AI/klavis',
        'https://github.com/morphik-org/morphik-core',
        'https://github.com/tinfoilsh/tinfoil-cli',
        'https://github.com/Operative-Sh/web-eval-agent',
        'https://github.com/better-auth/better-auth',
        'https://github.com/attunehq/attune',
        'https://github.com/pgdogdev/pgdog',
        'https://github.com/simstudioai/sim',
        'https://github.com/trycua/cua',
        'https://github.com/authed-dev/authed',
        'https://github.com/plexe-ai/plexe',
        'https://github.com/assistant-ui/assistant-ui',
        'https://github.com/TrainLoop/sdk',
        'https://github.com/gregpr07/browser-use',
        'https://github.com/pig-dot-dev/pig-python',
        'https://github.com/tensorpool/tensorpool',
        'https://github.com/roarkhq/sdk-roark-analytics-node',
        'https://github.com/mastra-ai/mastra',
        'https://github.com/confident-ai/deepeval',
        'https://github.com/Bindwell/PLAPT',
        'https://github.com/asteroidai/cookbook',
        'https://github.com/a1baseai/a1framework',
        'https://github.com/truffle-ai/truffle-ai-sdk',
        'https://github.com/superglue-ai/superglue',
        'https://github.com/subtrace/subtrace',
        'https://github.com/partcleda/partcleda.github.io',
        'https://github.com/cartography-cncf/cartography',
        'https://github.com/onlook-dev/onlook',
    ],
    "YC_2024": [
        'https://github.com/humanlayer/12-factor-agents',
        'https://github.com/diffusionstudio/core',
        'https://github.com/johnyeocx/autumn',
        'https://github.com/lingodotdev/lingo.dev',
        'https://github.com/circlemind-ai/fast-graphrag',
        'https://github.com/vespperhq/vespper',
        'https://github.com/trypear/pearai-master',
        'https://github.com/freestyle-sh/cloudstate',
        'https://github.com/patched-codes/patchwork',
        'https://github.com/General-Analysis/GA',
        'https://github.com/voideditor/void',
        'https://github.com/rowboatlabs/rowboat',
        'https://github.com/diodeinc/atopile-analyzer',
        'https://github.com/ZeroPathAI/zeropath-mcp-server',
        'https://github.com/heroui-inc/heroui',
        'https://github.com/lmnr-ai/lmnr',
        'https://github.com/eclipse-zenoh/zenoh',
        'https://github.com/zenbase-ai/core',
        'https://github.com/gauge-sh/tach',
        'https://github.com/minusxai/minusx',
        'https://github.com/aditya-nadkarni/spongecake',
        'https://github.com/EdisonLabs-Inc/CodeViz-Public',
        'https://github.com/stack-auth/stack-auth',
        'https://github.com/unslothai/unsloth',
        'https://github.com/synnaxlabs/synnax',
        'https://github.com/glasskube/glasskube',
        'https://github.com/mem0ai/mem0',
        'https://github.com/quivrhq/quivr',
        'https://github.com/Titan-Systems/titan',
        'https://github.com/hatchet-dev/hatchet',
        'https://github.com/getzep/zep',
        'https://github.com/lumina-ai-inc/chunkr',
        'https://github.com/elodin-sys/elodin',
        'https://github.com/devflowinc/trieve',
        'https://github.com/PySpur-com/PySpur',
        'https://github.com/phospho-app/phospho-legacy',
        'https://github.com/explodinggradients/ragas',
        'https://github.com/gventuri/pandas-ai',
        'https://github.com/getomni-ai/zerox',
        'https://github.com/atopile/atopile',
        'https://github.com/vercel/ai-chatbot',
        'https://github.com/buster-so/buster-platform',
        'https://github.com/nuanced-dev/nuanced',
        'https://github.com/TracecatHQ/tracecat',
        'https://github.com/ubicloud/ubicloud',
        'https://github.com/ssoready/ssoready',
        'https://github.com/SciPhi-AI/R2R',
        'https://github.com/gumloop/guMCP',
        'https://github.com/onyx-dot-app/onyx',
        'https://github.com/celest-dev/celest',
    ],
    "YC_2023": [
        'https://github.com/StructuredLabs/preswald',
        'https://github.com/srcbookdev/srcbook',
        'https://github.com/FlowiseAI/Flowise',
        'https://github.com/paradedb/paradedb',
        'https://github.com/ueberdosis/tiptap',
        'https://github.com/Silimate/silisizer',
        'https://github.com/khoj-ai/khoj',
        'https://github.com/continuedev/continue',
        'https://github.com/redotvideo/revideo',
        'https://github.com/refinedev/refine',
        'https://github.com/epsilla-cloud/vectordb',
        'https://github.com/Skyvern-AI/skyvern/tree/main/integrations/mcp',
        'https://github.com/briefercloud/briefer',
        'https://github.com/tegonhq/tegon',
        'https://github.com/atla-ai/atla-mcp-server',
        'https://github.com/opentoolsteam/cli',
        'https://github.com/cedana/cedana',
        'https://github.com/DioxusLabs/dioxus',
        'https://github.com/xeol-io/xeol',
        'https://github.com/twentyhq/twenty',
        'https://github.com/reworkd/AgentGPT',
        'https://github.com/artie-labs/transfer',
        'https://github.com/moonrepo/moon',
        'https://github.com/BerriAI/litellm',
        'https://github.com/Escape-Technologies/graphql-armor',
        'https://github.com/fern-api/fern',
        'https://github.com/evefancom/evefan',
        'https://github.com/rivet-gg/actor-core',
        'https://github.com/invopop/gobl',
        'https://github.com/keephq/keep',
        'https://github.com/playht/pyht',
        'https://github.com/odigos-io/odigos',
        'https://github.com/boundaryml/baml',
        'https://github.com/Helicone/helicone',
        'https://github.com/openmeterio/openmeter',
        'https://github.com/langfuse/langfuse',
        'https://github.com/FrigadeHQ/trench',
        'http://github.com/adap/flower',
        'https://github.com/NangoHQ/nango',
        'https://github.com/depot/bake-action',
        'https://github.com/DrDroidLab/PlayBooks',
        'https://github.com/triggerdotdev/trigger.dev',
        'https://github.com/traceloop/openllmetry',
        'https://github.com/reflex-dev/reflex',
        'https://github.com/middleware-labs/agent-apm-python',
        'https://github.com/tremorlabs/tremor',
        'http://github.com/highlight/highlight',
        'https://github.com/DAGWorks-Inc/hamilton',
    ],
    "YC_2022": [
        'https://github.com/mendableai/firecrawl',
        'https://github.com/laminlabs/lamindb',
        'https://github.com/metriport/metriport',
        'https://github.com/Mintplex-Labs/anything-llm',
        'https://github.com/nucleuscloud/neosync',
        'https://github.com/activepieces/activepieces',
        'https://github.com/codecrafters-io/build-your-own-x',
        'https://github.com/customeros/customeros',
        'https://github.com/dittofeed/dittofeed',
        'https://github.com/medplum/medplum',
        'https://github.com/gravitl/netmaker',
        'https://github.com/ploomber/jupysql',
        'https://github.com/argumentcomputer/LSpec',
        'https://github.com/CypherD-IO/mobile-app',
        'https://github.com/botcity-dev/botcity-framework-core-python',
        'https://github.com/voize-gmbh/reakt-native-toolkit',
        'https://github.com/tuva-health/FHIR_inferno',
        'https://github.com/mintlify/starter',
        'https://github.com/iomete/dbt-iomete',
        'https://github.com/pingdotgg/uploadthing',
        'https://github.com/flagright/flagright-node',
        'https://github.com/its-dart/dart-mcp-server',
        'https://github.com/beam-cloud/beta9',
        'https://github.com/lancedb/lancedb',
        'https://github.com/firezone/firezone',
        'https://github.com/elementary-data/elementary',
        'https://github.com/growthbook/growthbook',
        'https://github.com/hyperdxio/hyperdx',
        'https://github.com/requestly/requestly',
        'https://github.com/grai-io/grai-core',
    ],
    "YC_2021": [
        'https://github.com/lightly-ai/lightly',
        'https://github.com/evidence-dev/evidence',
        'https://github.com/bytebot-ai/bytebot',
        'https://github.com/evidentlyai/evidently',
        'https://github.com/mergentlabs/mergent-js',
        'https://github.com/Cloudanix/docs',
        'https://github.com/enso-org/enso',
        'https://github.com/hyperbrowserai/HyperAgent',
        'https://github.com/getlago/lago',
        'https://github.com/joindeed/prisma-auth',
        'https://github.com/carbonfact/lea',
        'https://github.com/pipekit/argo-workflows-ci-example',
        'https://github.com/superwall/Superwall-iOS',
        'https://github.com/hotgluexyz/gluestick',
        'https://github.com/artilleryio/artillery',
        'https://github.com/openlayer-ai/openlayer-python',
        'https://github.com/ollama/ollama',
        'https://github.com/wasp-lang/open-saas',
        'https://github.com/svix/svix-webhooks',
        'https://github.com/infracost/infracost',
        'https://github.com/chatwoot/chatwoot',
        'https://github.com/lunatic-solutions/lunatic',
        'https://github.com/SimplifyJobs/Summer2025-Internships',
        'https://github.com/datrics-ai/text2sql',
        'https://github.com/mindee/doctr',
        'https://github.com/fintoc-com/fintoc-python',
        'https://github.com/laudspeaker/laudspeaker',
        'https://github.com/aspen-cloud/triplit',
        'https://github.com/SigNoz/charts',
        'https://github.com/humaans/next-img',
        'https://github.com/beeper/bridge-manager',
        'https://github.com/dyte-io/docs',
        'https://github.com/promotedai/ios-metrics-sdk',
    ],
    "YC_2020": [
        'https://github.com/Fieldguide/action-hasura-change-summary',
        'https://github.com/mito-ds/mito',
        'https://github.com/supabase/auth',
        'https://github.com/seamapi/docs',
        'https://github.com/questdb/questdb',
        'https://github.com/lightdash/lightdash',
        'https://github.com/supertokens/docs',
        'https://github.com/Increase/increase-python',
        'https://github.com/jitsucom/jitsu',
        'https://github.com/ukama/ukama',
        'https://github.com/jet-admin/jet-bridge',
        'https://github.com/airbytehq/airbyte',
        'https://github.com/recallai/voice-agent-demo',
        'https://github.com/raycast/script-commands',
        'https://github.com/Photoroom/datago',
        'https://github.com/buildbuddy-io/buildbuddy',
        'https://github.com/querypie/querypie-mcp-server',
        'https://github.com/signadot/hotrod',
        'https://github.com/superfly/corrosion',
        'https://github.com/replicate/cog',
        'https://github.com/mindsdb/mindsdb',
        'https://github.com/metaplane/dbt-expectations',
        'https://github.com/withfig/autocomplete',
        'https://github.com/piepacker/JamPadCompose',
    ],
    "YC_2019": [
        'https://github.com/Recidiviz/pulse-data',
        'https://github.com/rainbow-me/rainbow',
        'https://github.com/openreplay/openreplay',
        'https://github.com/Localitos/pluto',
        'https://github.com/embrace-io/embrace-android-sdk',
        'https://github.com/MethodFi/method-node',
        'https://github.com/trycourier/courier-node',
        'https://github.com/oven-sh/bun',
        'https://github.com/truora/minidyn',
        'https://github.com/votingworks/arlo',
        'https://github.com/rune/rune',
        'https://github.com/glideapps/glide-data-grid',
        'https://github.com/dagger/dagger',
    ],
    "YC_2018": [
        'https://github.com/activeloopai/deeplake',
        'https://github.com/RevenueCat/cat-paywall-compose',
        'https://github.com/Modern-Treasury/modern-treasury-python',
        'https://github.com/Worklytics/psoxy',
    ]
}

module.exports = { all_Repos }